import pygame

RESTART_EVENT = pygame.USEREVENT + 1
PREVIOUS_EVENT = pygame.USEREVENT + 2
NEXT_EVENT = pygame.USEREVENT + 3
RANDOM_GAME_EVENT = pygame.USEREVENT + 4
SOLVE_BFS_EVENT = pygame.USEREVENT + 5
SOLVE_ASTARMAN_EVENT = pygame.USEREVENT + 6
SOLVE_DIJKSTRA_EVENT = pygame.USEREVENT + 7
SOLVE_GBFS_EVENT = pygame.USEREVENT + 8
SOLVE_USC_EVENT = pygame.USEREVENT + 9
BENCHMARK_ALL_METHOD = pygame.USEREVENT + 10